### PR TITLE
Update embedded-hal dependency to 1.0.0-alpha.7

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by almindor** [comment]
Looking good! I wonder if we should wait for https://github.com/rust-embedded/embedded-hal/pull/351 to land so we can update our SPI to it (since it's almost the same split). @Disasm what are your thoughts?

**Comment by almindor** [comment]
@ahmedcharles we'll need to bump the MSRV for this as well, including the CI scripts to match.

**Comment by ahmedcharles** [comment]
Sure, as I mentioned in another similar PR in a related repo, I'm just trying to get it all to compile/work before I propose a precise plan for releasing/merging it.

I'm fine with updating to using the new SPI interface once it's in an alpha.

**Comment by almindor** [comment]
I'm going to merge this as a step to get `embedded-hal` to `alpha.8` with the SPI split next (I'll try to get a PR for that going soon).

**Comment by almindor** [comment]
@ahmedcharles I've had to revert this (and subsequent changes) since I found an odd problem with the SPI that only happened with release mode. I'm going to investigate in a new PR. There was also a logical error in the `spi/bus.rs` [here](https://github.com/riscv-rust/e310x-hal/pull/42/files#diff-772c71e3a9710c91232448970dab0890fa827c9027c7338ccc02c0972717f5cdR135) the comparison should've been with `iwrite`. Even fixing that tho, the `--release` SPI failure was still there. I'll try to test these changes bit by bit to see where the problem occurs with the new PR.

**Pull request merged**
